P5 E-learning/force-app/main/default/objects/Respuesta__c/Respuesta__c.object-meta.xml
<CustomObject>
    <label>Respuesta</label>
    <nameField>
        <label>Respuesta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Respuestas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-learning/force-app/main/default/objects/Respuesta__c/fields/Es_Correcta__c.field-meta.xml
<CustomField>
    <fullName>Es_Correcta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si tildamos es la opcion correcta a tener en cuenta</description>
    <inlineHelpText>Si tildamos es la opcion correcta a tener en cuenta</inlineHelpText>
    <label>Es Correcta?</label>
    <type>Checkbox</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/RespuestaResponse__c/RespuestaResponse__c.object-meta.xml
<CustomObject>
    <description>Los registros son las respuestas que el usuario selecciona como &quot;respondidas&quot;, se referencia a una pregunta y unidad respectivamente.</description>
    <label>RespuestaResponse</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>RespuestaResponse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RespuestaResponses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P5 E-learning/force-app/main/default/objects/RespuestaResponse__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Respuesta</label>
    <referenceTo>Respuesta__c</referenceTo>
    <relationshipLabel>RespuestaResponses</relationshipLabel>
    <relationshipName>RespuestaResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/RespuestaResponse__c/fields/UnidadUser__c.field-meta.xml
<CustomField>
    <fullName>UnidadUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UnidadUser</label>
    <referenceTo>UnidadUser__c</referenceTo>
    <relationshipLabel>RespuestaResponses</relationshipLabel>
    <relationshipName>RespuestaResponses</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/Unidad__c/Unidad__c.object-meta.xml
<CustomObject>
    <label>Unidad</label>
    <nameField>
        <label>Unidad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unidades</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-learning/force-app/main/default/objects/Unidad__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/UnidadUser__c/UnidadUser__c.object-meta.xml
<CustomObject>
    <label>UnidadUser</label>
    <nameField>
        <displayFormat>UU-{0000}</displayFormat>
        <label>UnidadUser Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UnidadesUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P5 E-learning/force-app/main/default/objects/UnidadUser__c/fields/EstadoUnidad__c.field-meta.xml
<CustomField>
    <fullName>EstadoUnidad__c</fullName>
    <label>EstadoUnidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

P5 E-learning/force-app/main/default/objects/UnidadUser__c/fields/Intento__c.field-meta.xml
<CustomField>
    <fullName>Intento__c</fullName>
    <label>Intento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/UnidadUser__c/fields/Puntos__c.field-meta.xml
<CustomField>
    <fullName>Puntos__c</fullName>
    <label>Puntos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P5 E-learning/force-app/main/default/objects/UnidadUser__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidad</label>
    <referenceTo>Unidad__c</referenceTo>
    <relationshipLabel>UnidadesUsers</relationshipLabel>
    <relationshipName>UnidadesUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

P5 E-learning/force-app/main/default/classes/UnitResponseTrigger.cls
public with sharing  class UnitResponseTrigger { 

    public static void checkUpdate(List<UnidadUser__c> unidaduserlist,  Map<Id,UnidadUser__c> mapUnit){  //recibe una Lista tipo unidaduser  dentro de la variable unidaduserlist dontre entra el trigger.new
        List<UnidadUser__c> listavalidar = new List<UnidadUser__c>();
        for(UnidadUser__c dumyu: unidaduserlist ){
             If(dumyu.EstadoUnidad__c == 'Answered'  && mapUnit.get(dumyu.id).EstadoUnidad__c == 'draft'){
                listavalidar.add(dumyu);
            }
         }
        checkearRespuestas(listavalidar); //antes de irme del metodo que hace el check previo update,ejecuto el validador de respuestas... notar que nunca paso realmente a Answered
    }
    
    public static void checkearRespuestas(List<UnidadUser__c> unidaduserlist){ //creo un metodo para validar las respuestas
        Map <id, UnidadUser__c> mapfilter = new map <id, UnidadUser__c> ([SELECT id, unidad__r.Puntos__c, (SELECT Respuesta__r.Es_Correcta__c from RespuestaResponses__r) FROM UnidadUser__c WHERE ID =: unidaduserlist]);
        
        	for (UnidadUser__c dumy : unidaduserlist){
                integer contador =0;
           		 for (RespuestaResponse__c respuestas : mapfilter.get(dumy.id).RespuestaResponses__r){                        
                    if (respuestas.Respuesta__r.Es_Correcta__c == true){
                        contador ++;
                    }    
            	}
            
            	if(contador == Mapfilter.get(dumy.id).RespuestaResponses__r.size()){
                    dumy.EstadoUnidad__c = 'Success';    
                            if(dumy.Intento__c == 1){
                                   dumy.puntos__c = Mapfilter.get(dumy.id).unidad__r.puntos__c;
                            }else if(dumy.Intento__c == 2){
                                  dumy.puntos__c = Mapfilter.get(dumy.id).unidad__r.puntos__c/2;
                            }else
                            { dumy.puntos__c = Mapfilter.get(dumy.id).unidad__r.puntos__c/4;
                                        }
           		 }else{
		              dumy.EstadoUnidad__c= 'Fail';
             	  }	
        
   	 	}
	}
    
}